name: "potato actions"

on:
  pull_request:
  push:

jobs:
  build-and-run:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-20.09
      - run: cd hs && nix-shell --run "cabal build"
      - run: make -C cpp run

